# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f48df305781ddb7463912b773e4cb1b5"
name = "qu code genaretor"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
